In [112]:
#************Question1:

import numpy as np

np=np.array((1,2,3,4))

print(np)

[1 2 3 4]


In [113]:
l = np.tolist()

print(l)

[1, 2, 3, 4]


In [114]:
#************Question2:

import numpy as np 
  
n_array = np.array([[55, 25, 15], 
                    [30, 44, 2], 
                    [11, 45, 77]]) 
  

print(n_array) 


[[55 25 15]
 [30 44  2]
 [11 45 77]]


In [115]:
trace = np.trace(n_array) 
  
print(trace) 

176


In [116]:
#************Question3:
x=input()
import numpy as np
n_array = np.array([[1, 2], 
                    [3,5]])
i=0
D=[]
L = n_array.reshape(1,-1)
while i < L.shape[1]:
    if L[0,i] > int(x):
        D.append(L[0,i])
    i=i+1  
    
print("les valeur sont :",D)

 2


les valeur sont : [3, 5]


In [117]:
#************Question4:

import numpy as np

A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [118]:
C=np.add(A, B)
print(C)

[[ 6  8]
 [10 12]]


In [23]:
#************Question5:

In [119]:
import numpy as np

T=np.array([[10, 20, 30],
       [3, 50, 5],
       [70, 80, 90],
       [100, 110, 120]])



In [120]:
print(T)

print("La Moyenne de chaque ligne :", np.mean(T,axis=1))

[[ 10  20  30]
 [  3  50   5]
 [ 70  80  90]
 [100 110 120]]
La Moyenne de chaque ligne : [ 20.          19.33333333  80.         110.        ]
